CEN3031-group16/GroupProject

source/Dialogs.py, source/ScrumblesData.py
Resolves issue #38
Resolves issue #39
Resolves issue #40
=> Resolve issues38 40

source/Dialogs.py, source/masterView.py
=> Issue42 create item dialog

source/Scrumbles.py, source/itemMangerView.py, source/masterView.py
=> Item Manager View

source/Dialogs.py, source/ScrumblesData.py, source/ScrumblesFrames.py, source/ScrumblesObjects.py, source/backlogView.py, source/masterView.py
=> Project queries -> Sprint 2

source/Dialogs.py, source/Scrumbles.py, source/ScrumblesData.py, source/ScrumblesFrames.py, source/ScrumblesObjects.py, source/backlogView.py, source/masterView.py
#87 
Implemented issue #87 
3 hrs of coding
Edit item allows the assigning of items to Sprints and Users
=> Issue 87 item edit

source/Dialogs.py, source/masterView.py
=> Group project 85

source/Dialogs.py, source/Scrumbles.py, source/ScrumblesData.py, source/ScrumblesFrames.py, source/backlogView.py, source/developerHomeView.py, source/itemMangerView.py, source/loginView.py, source/mainView.py, source/masterView.py
#102  Implement Better Update Policy
Scrumbles is now multithreaded and socketed.  She runs so much faster.
=> Implement better update

serverScripts/mysqlport/mysqlportreporter.py, serverScripts/mysqlport/threadServer.py, serverScripts/mysqlportListen.sh, serverScripts/readme.txt, source/Dialogs.py, source/Scrumbles.py, source/ScrumblesData.py, source/ScrumblesFrames.py, source/ScrumblesObjects.py, source/backlogView.py, source/developerHomeView.py, source/itemMangerView.py, source/loginView.py, source/mainView.py, source/masterView.py, source/remoteUpdate.py, source/testing/getChangeUpdate.py, source/testing/login.txt, source/testing/testDataBlock.py, source/testing/testDriveUpdater.py
Implemented a threaded and socketed datablock class that will gather all data from database and self update when a remote change is made.
with a bit of wizardry class is also capable of automagically updating lists inside of frames with DataBlock.packCallbacks() method.  Simply write a function that will update your local list, pass that function name to datablock object. And *POOF* *Alakazam*  Your list will be auto-updated only when an a change occurs on the remote database. 
Study testing/testDataBlock.py  for example use case
Total dev TIME = 29hrs
Resolves Issue #60
=> Remote updates

source/ScrumblesFrames.py
I changed the search function in Scrumbles frames to be case insensitive
=> changed backlog search to be case insensitive

source/Dialogs.py, source/ScrumblesData.py, source/backlogView.py
=> Fix broken edit dialog

source/Dialogs.py, source/ScrumblesData.py, source/ScrumblesFrames.py, source/ScrumblesObjects.py, source/developerHomeView.py, source/masterView.py
Implements Project Members and Project Items  …
Item.projectID is not in database.  Item.projectID is in app only and is initialized to 0
IF item.projectID == 0
item is not in a project
New dataBlock objects:
addUserToProject(ScrumblesObjects.Project,SrcrumblesObjects.User)
removeUserFromProject(ScrumblesObjects.Project,ScrumblesObjects.User)
addItemToProject(SrumcblesObjects.Project,ScrumblesObjects.Item)
removeItemFromPRojects(ScurmblesObjecs.Project,ScrumblesObjects.Item)
New Lists to ScrumblesObjects.Project
listOfAssingedUsers
listOfAssignedItems
New List in ScrumblesOBjects.User
listOfProjects
A Scrumbles TEAM is the list: SrumblesObjects.Project.listOfAssignedUsers
=> Impliment project to user relationship

source/ScrumblesData.py, source/testing/syncTables.py
code allowed assignment of users or items to project more than once.
This fixes that
Also add a debugDump for dataBlock
=> Duplicate data bug fix

source/Dialogs.py
=> Add Date Field to create sprint

source/Dialogs.py, source/ScrumblesData.py, source/ScrumblesObjects.py, source/loginView.py, source/mainView.py, source/masterView.py
=> Items Now Have Points

source/Dialogs.py, source/ScrumblesData.py, source/ScrumblesFrames.py, source/ScrumblesObjects.py, source/backlogView.py
still need at item assigned to a project but not assigned to sprint to make sure it shows up red
=> Sprint2 electric bugaloo

source/ScrumblesFrames.py, source/ScrumblesObjects.py, source/developerHomeView.py, source/mainView.py, source/masterView.py, source/teamView.py
Issues #122, #116, #111 
Note: #122 needs to be tested with last night's bug fixes
For feature details see commits
=> Sprint2 night shift

source/masterView.py
=> tweaked geometry of masterview

source/ScrumblesFrames.py
=> Fixes Comment class from previous merge

serverScripts/CreateScrumblesDB.sql
Adds SQL script to serverScripts
Execute Script on MySQL Database to generate all the necessary tables for use by Scrumbles application.
Creates a default project and default user Admin with default pw Admin1011
Script to be used for new installations of the Scrumbles Application System
Need to create a First Instance Method for Scrumbles as well.  Method should check for the existence of a config file.  If the config file is not present, a dialog should open requesting the Database IP address, Database Login and Password.  Upon successful login into the Database, method will write the parameters to the login config file.
=> Create Scrumbles Database SQL Script

source/DataBlock.py, source/Dialogs.py, source/Query.py, source/SPopMenu.py, source/ScrumblesData.py, source/ScrumblesObjects.py
Resolves ISSUE #209 
Resolves ISSUE #164 
Resolves ISSUE #169 
Resolves ISSUE #136
=> Sanitze inputs

source/Dialogs.py, source/Query.py, source/SDynamics.py, source/SLists.py, source/SPopMenu.py, source/backlogManagerView.py, source/developerHomeView.py
Adds the pop-up Menus to the UX
add codelink to SCardDescription and made the link clickable
=> Dev home popup menu

source/DataBlock.py, source/Query.py, source/testing/syncTables.py
add exception hangling for key error that will attempt to reload keys
If key is not present, database is not correct
=> Fix Query Error adding a new item to the timeline

source/SDynamics.py
#241 
commentField is scrollable
=> Scrolling comments

source/DataBlock.py, source/Dialogs.py, source/SPopMenu.py, source/backlogManagerView.py, source/developerHomeView.py, source/loginView.py, source/mainView.py, source/masterView.py, source/sprintManagerView.py, source/testing/test_genericDialog.py
=> Sprint edit dialog

source/DataBlock.py, source/masterView.py, source/sprintManagerView.py
with R-Clik
Tweaked Thread timing bugfix? #256  Needs more testing
Add menu item  Help->Refresh data (work-around for #256
=> Scrum Master can now assign users and approve items in Sprint View 

source/Dialogs.py, source/SDynamics.py, source/masterView.py
Linux compatibility Bug Fixes
#265
=> Bug fix265

source/SDynamics.py
=> Comment+dynamic bug fixes

source/SPopMenu.py
=> Fix Broken assign to epic

source/SDynamics.py
I have to sleep now sadly, can someone check to see if this really fixes the bug or just moves it somewhere else.
=> Seems to fix the bug

source/DataBlock.py, source/Dialogs.py, source/Query.py, source/SDynamics.py, source/SPopMenu.py, source/ScrumblesData.py, source/ScrumblesObjects.py, source/backlogManagerView.py, source/developerHomeView.py
Promote to  Epic wasn't working either.
also added background methods to wipe an item from the database
with `def deleteScrumblesObject(self,obj):`
=> Demote from epic not working

source/SDynamics.py, source/mainView.py
Fixed a minor UI issue in the main view so it shows as Sprint Description on the top. Fixed item query error for the 3rd item box. Got some help from Jesse.
=> Minor Fixes in MainView

source/views/mainView.py, source/views/masterView.py, source/views/splashView.py
Implemented empty project check for user on log in
=> Sprint3 kyle stuff2

source/frames/SDynamics.py, source/views/developerHomeView.py
Progress bars look like they're working well
=> Progress Bar in Sprint Description Card

source/views/analyticsView.py
=> Fixed bug with progress bar colors from analyticsView 

source/views/masterView.py
Formatting got messed up in the last pull
=> Formatting to masterView

source/frames/SprintDialogs.py
=> import datetime... oops
